<?xml version="1.0"?>

<robot name="limo_ackerman" xmlns:xacro="http://ros.org/wiki/xacro">
    <!-- a lightweight robot geometry model -->
    <xacro:arg name="model_lite" default="true" />
	
    <xacro:include filename="$(find limo_description)/urdf/limo_properties.xacro" />
    <xacro:include filename="$(find limo_description)/urdf/limo_ackerman/limo_ackerman.gazebo" />
    
    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>

    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.13" />
    <xacro:property name="base_y_size" value="0.12" />
    <xacro:property name="base_z_size" value="0.1" />
  
    <xacro:property name="wheelbase" value="0.2"/>
    <xacro:property name="track" value="0.13"/>
    <xacro:property name="wheel_vertical_offset" value="-0.10" />
    <xacro:property name="base_mass" value="2.1557"/>

    
    <!-- <xacro:property name="wheel_length" value="0.045" /> -->
    <xacro:property name="wheel_length" value="0.001" />
    <xacro:property name="wheel_radius" value="0.045" />

    <link name="base_link">
        <visual>
            <origin xyz="0 0 -0.15" rpy="0 0 1.57" />
            <geometry>
                 <mesh filename="file://$(find limo_description)/meshes/limo_base_lite.dae" scale="1 1 1"/> 
               <!-- <mesh filename="file://$(find limo_description)/meshes/limo_optimal.dae" scale="1 1 1"/>  -->
            </geometry>
        </visual>
        <collision>
            <!--origin xyz="0 0 -0.15" rpy="0 0 1.57" /-->
            <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
              <box size="${base_x_size} ${base_y_size} ${base_z_size}"/>
          </geometry>
        </collision>
    </link>

    <link name="inertial_link">
        <inertial>
            <origin xyz="0.0 0.0 0.0" />
            <mass value="${base_mass}" />
            <inertia ixx="0.0043832566666666675" ixy="0" ixz="0" 
                     iyy="0.004832360833333334" iyz="0" 
                     izz="0.005622784166666667" />
        </inertial>
    </link>
    
    <link name="base_footprint"/>

    <joint name="base_joint" type="fixed">
      <parent link="base_link"/>
      <child link="base_footprint"/>
      <origin xyz="0.0 0.0 0.15" rpy="0 0 0"/>
    </joint>
    

    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>

    <xacro:limo_laser parent_prefix="base_link" frame_prefix="laser">
        <origin xyz="0.103 0 -0.034" rpy="0 0 0"/>
    </xacro:limo_laser>

    <xacro:limo_depth_camera parent_prefix="base_link" frame_prefix="depth_camera">
        <!-- <origin xyz="0.084 0 0.3" rpy="0 0 0"/> -->
        <origin xyz="0.084 0 0.026" rpy="0 0 0"/>
    </xacro:limo_depth_camera>
    
    <xacro:limo_imu parent_prefix="base_link" frame_prefix="imu">
        <origin xyz="0.0 0 -0.1" rpy="0 0 0"/>
    </xacro:limo_imu>


  <xacro:limo_left_steering_hinge parent_prefix="base_link" wheel_prefix="front_left">
    <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0  0" />
  </xacro:limo_left_steering_hinge>

  <xacro:limo_right_steering_hinge parent_prefix="base_link" wheel_prefix="front_right">
    <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
  </xacro:limo_right_steering_hinge>


        <link name="main_steering_link">
            <inertial>
              <mass value="0.25" />
              <inertia ixx="0.00525" ixy="0" ixz="0" iyy="0.00035" iyz="0" izz="0.00525" />
              <origin xyz="0 0 0" />

            </inertial>
            <!--<visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                  <mesh filename="file://$(find limo_description)/meshes/steering.dae"/>
                </geometry>
            </visual> -->

        </link>

        <joint name="main_steering" type="revolute">
            <parent link="base_link"/>
            <child link="main_steering_link"/>
            <origin xyz="${wheelbase/2} 0.0 ${wheel_vertical_offset * -2.0}" rpy="${M_PI} 0 0" />
            <axis xyz="0 0 -1" />
            <limit lower="-0.523598767" upper="0.523598767" effort="1000" velocity="10.0" />
            <dynamics damping="0.0" friction="0.0"/>
        </joint>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_left" reflect="1" model_lite="$(arg model_lite)">
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:limo_wheel>

    <xacro:limo_wheel parent_prefix="base_link" wheel_prefix="rear_right" reflect="-1" model_lite="$(arg model_lite)">
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="${M_PI} 0 0" />
    </xacro:limo_wheel>



</robot>
